# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/health/health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "app/proto/health/health.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x61pp/proto/health/health.proto\x12\x06health"\x0f\n\rHealthRequest" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2@\n\x06Health\x12\x36\n\x05\x43heck\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "app.proto.health.health_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHREQUEST"]._serialized_start = 41
    _globals["_HEALTHREQUEST"]._serialized_end = 56
    _globals["_HEALTHRESPONSE"]._serialized_start = 58
    _globals["_HEALTHRESPONSE"]._serialized_end = 90
    _globals["_HEALTH"]._serialized_start = 92
    _globals["_HEALTH"]._serialized_end = 156
# @@protoc_insertion_point(module_scope)
