# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: app/proto/user/user.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client

if typing.TYPE_CHECKING:
    import grpclib.server

import app.proto.user.user_pb2


class UserBase(abc.ABC):
    @abc.abstractmethod
    async def SignUp(
        self,
        stream: "grpclib.server.Stream[app.proto.user.user_pb2.SignUpRequest, app.proto.user.user_pb2.UserResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def EditProfile(
        self,
        stream: "grpclib.server.Stream[app.proto.user.user_pb2.EditProfileRequest, app.proto.user.user_pb2.UserResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Login(
        self,
        stream: "grpclib.server.Stream[app.proto.user.user_pb2.LoginRequest, app.proto.user.user_pb2.LoginResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/user.User/SignUp": grpclib.const.Handler(
                self.SignUp,
                grpclib.const.Cardinality.UNARY_UNARY,
                app.proto.user.user_pb2.SignUpRequest,
                app.proto.user.user_pb2.UserResponse,
            ),
            "/user.User/EditProfile": grpclib.const.Handler(
                self.EditProfile,
                grpclib.const.Cardinality.UNARY_UNARY,
                app.proto.user.user_pb2.EditProfileRequest,
                app.proto.user.user_pb2.UserResponse,
            ),
            "/user.User/Login": grpclib.const.Handler(
                self.Login,
                grpclib.const.Cardinality.UNARY_UNARY,
                app.proto.user.user_pb2.LoginRequest,
                app.proto.user.user_pb2.LoginResponse,
            ),
        }


class UserStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SignUp = grpclib.client.UnaryUnaryMethod(
            channel,
            "/user.User/SignUp",
            app.proto.user.user_pb2.SignUpRequest,
            app.proto.user.user_pb2.UserResponse,
        )
        self.EditProfile = grpclib.client.UnaryUnaryMethod(
            channel,
            "/user.User/EditProfile",
            app.proto.user.user_pb2.EditProfileRequest,
            app.proto.user.user_pb2.UserResponse,
        )
        self.Login = grpclib.client.UnaryUnaryMethod(
            channel,
            "/user.User/Login",
            app.proto.user.user_pb2.LoginRequest,
            app.proto.user.user_pb2.LoginResponse,
        )
