# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user/user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "app/proto/user/user.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x61pp/proto/user/user.proto\x12\x04user"d\n\rSignUpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t"h\n\x12\x45\x64itProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ndepartment\x18\x05 \x01(\t"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"]\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ndepartment\x18\x05 \x01(\t"@\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12 \n\x04user\x18\x02 \x01(\x0b\x32\x12.user.UserResponse2\xa8\x01\n\x04User\x12\x31\n\x06SignUp\x12\x13.user.SignUpRequest\x1a\x12.user.UserResponse\x12;\n\x0b\x45\x64itProfile\x12\x18.user.EditProfileRequest\x1a\x12.user.UserResponse\x12\x30\n\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "app.proto.user.user_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SIGNUPREQUEST"]._serialized_start = 35
    _globals["_SIGNUPREQUEST"]._serialized_end = 135
    _globals["_EDITPROFILEREQUEST"]._serialized_start = 137
    _globals["_EDITPROFILEREQUEST"]._serialized_end = 241
    _globals["_LOGINREQUEST"]._serialized_start = 243
    _globals["_LOGINREQUEST"]._serialized_end = 293
    _globals["_USERRESPONSE"]._serialized_start = 295
    _globals["_USERRESPONSE"]._serialized_end = 388
    _globals["_LOGINRESPONSE"]._serialized_start = 390
    _globals["_LOGINRESPONSE"]._serialized_end = 454
    _globals["_USER"]._serialized_start = 457
    _globals["_USER"]._serialized_end = 625
# @@protoc_insertion_point(module_scope)
